//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.ServiceReferenceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWCF.ITimeService")]
    public interface ITimeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeService/GetDayFromData", ReplyAction="http://tempuri.org/ITimeService/GetDayFromDataResponse")]
        string GetDayFromData(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeService/GetDayFromData", ReplyAction="http://tempuri.org/ITimeService/GetDayFromDataResponse")]
        System.Threading.Tasks.Task<string> GetDayFromDataAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeServiceChannel : WCF.Client.ServiceReferenceWCF.ITimeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeServiceClient : System.ServiceModel.ClientBase<WCF.Client.ServiceReferenceWCF.ITimeService>, WCF.Client.ServiceReferenceWCF.ITimeService {
        
        public TimeServiceClient() {
        }
        
        public TimeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayFromData(System.DateTime date) {
            return base.Channel.GetDayFromData(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayFromDataAsync(System.DateTime date) {
            return base.Channel.GetDayFromDataAsync(date);
        }
    }
}
